services:
  paytabs-app:
    build: docker/php-apache
    image: paytabs-php-8.4-apache
    container_name: paytabs-app
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - paytabs-mysql
    volumes:
      - ./:/var/www/html/
    networks:
      - paytabs-network-link

  paytabs-mysql:
    image: mysql:8.0
    container_name: paytabs_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: paytabs
      MYSQL_USER: paytabs_user
      MYSQL_PASSWORD: paytabs_user_pass
      MYSQL_ROOT_PASSWORD: paytabs_root_pass
    networks:
      - paytabs-network-link
    volumes:
      - database-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: paytabs-phpmyadmin
    restart: unless-stopped
    ports:
      - "8060:80"
    environment:
      PMA_HOST: paytabs_mysql
      PMA_PORT: 3306
      PMA_USER: paytabs_user
      PMA_PASSWORD: paytabs_user_pass
    depends_on:
      - paytabs-mysql
    networks:
      - paytabs-network-link

networks:
  paytabs-network-link:
    driver: bridge
    name: paytabs-network-link

volumes:
  database-data:
    name: paytabs-mysql-database
