services:
  paytabs-app:
    build: docker/php-apache
    image: paytabs-php-8.4-apache
    container_name: paytabs-app
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - paytabs-mysql
    volumes:
      - ./:/var/www/html
    networks:
      - paytabs-network-link

  paytabs-mysql:
    image: mysql:5.7
    container_name: '${DATABASE_HOST}'
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: '${DATABASE_NAME}'
      MYSQL_USER: '${DATABASE_USER}'
      MYSQL_PASSWORD: '${DATABASE_PASS}'
      MYSQL_ROOT_PASSWORD: '${DATABASE_ROOT_PASS}'
    networks:
      - paytabs-network-link
    volumes:
      - database-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: paytabs-phpmyadmin
    restart: unless-stopped
    ports:
      - "8060:80"
    environment:
      PMA_HOST: '${DATABASE_HOST}'
      PMA_PORT: 3306
      PMA_USER: '${DATABASE_USER}'
      PMA_PASSWORD: '${DATABASE_PASS}'
    depends_on:
      - paytabs-mysql
    networks:
      - paytabs-network-link

networks:
  paytabs-network-link:
    driver: bridge
    name: paytabs-network-link

volumes:
  database-data:
    name: paytabs-mysql-database
